---
version: "3.9"
services:
  snipe-it:
    image: snipeit_titans24:latest
    secrets:
      - source: app.key
    environment:
      APP_ENV: "develop"
      APP_DEBUG: "true"
      APP_KEY: "/run/secrets/app.key"
      APP_URL: "http://127.0.0.1:32782"
      APP_TIMEZONE: "Europe/Warsaw"
      APP_LOCALE: "en"
      DB_CONNECTION: "mysql"
      DB_PREFIX: "null"
      DB_DUMP_PATH: "/usr/bin"
      ENCRYPT: "false"
      IMAGE_LIB: "gd"
    ports:
      - "32782:80"

  snipe-db:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    networks:
      snipe-network:
    secrets:
      - source: db.root.pass
      - source: db.name
      - source: db.user
      - source: db.user.pass
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db.root.pass"
      MYSQL_DATABASE_FILE: "/run/secrets/db.name"
      MYSQL_PASSWORD_FILE: "/run/secrets/db.user.pass"
      MYSQL_USER_FILE: "/run/secrets/db.user"
      MYSQL_PORT_3306_TCP_ADDR: "http://127.0.0.1:32782"
      MYSQL_PORT_3306_TCP_PORT: 3306

volumes:
  mysql:
    driver: local
    name: "snipe-it--db"

networks:
  snipe-network:
    driver: overlay
    internal: true

secrets:
  app.key:
    external: true
    name: "snipe-it-app_app.key"
  db.root.pass:
    external: true
    name: "snipe-it-db_db.root.pass"
  db.name:
    external: true
    name: "snipe-it-db_db.name"
  db.user:
    external: true
    name: "snipe-it-db_db.user"
  db.user.pass:
    external: true
    name: "snipe-it-db_db.user.pass"
